[build]
builder = "nixpacks"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.healthcheck]
httpPath = "/api/v1/health"
initialDelaySeconds = 30
periodSeconds = 10
timeoutSeconds = 30
failureThreshold = 5
successThreshold = 1
