[build]
builder = "nixpacks"
nixpacksConfigPath = "backend"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
PORT = { default = "8000" }

[[services]]
[services.app]
source = "backend"
